name: Back-end Tests and Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Mise à jour vers la dernière version

      - name: Set up JDK 11
        uses: actions/setup-java@v3  # Mise à jour vers la dernière version
        with:
          java-version: '11'
          distribution: 'temurin'  # Ajout du paramètre distribution pour spécifier le JDK

      - name: Cache Maven dependencies
        uses: actions/cache@v3  # Mise à jour vers la dernière version
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean install

      - name: Run tests and generate coverage report
        run: mvn test jacoco:report

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: backend-coverage-report
          path: target/site/jacoco
