name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: 
      - 'back/**'
      - 'front/**'
  pull_request:
    branches: [main]
    types: [opened, reopened]
    paths: 
      - 'back/**'
      - 'front/**'

jobs:
  backend:
    runs-on: ubuntu-latest
    if: ${{github.event.review.state == 'approved' || (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'workflow_dispatch' }}

    defaults:
      run:
        working-directory: ${{ github.workspace }}/back

    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend Docker image
        run: |
          docker build -t bobapp-back .
          docker tag bobapp-back ${{ secrets.DOCKER_USERNAME }}/bobapp-back:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/bobapp-back:latest

  frontend:
    runs-on: ubuntu-latest
    if: ${{github.event.review.state == 'approved' || (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'workflow_dispatch' }}

    defaults:
      run:
        working-directory: ${{ github.workspace }}/front

    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push frontend Docker image
        run: |
          docker build -t bobapp-front .
          docker tag bobapp-front ${{ secrets.DOCKER_USERNAME }}/bobapp-front:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/bobapp-front:latest
